name: Build DRSuite
run-name: Build DRSuite by @${{ github.actor }}

on:
  workflow_dispatch:
  release:
    types: [created]
  push:
    branches: [main, dev]
  # pull_request:
  #   branches: [main]
env:
#  RELEASEVERSION: ${{ github.ref_name }}
  RELEASEVERSION: 25a
  MLM_LICENSE_TOKEN: ${{ secrets.MATLAB_TOKEN }}
  MATLAB_VERSION: R2025b
jobs:
  build:
    permissions: write-all
    name: Build DRSuite
    strategy:
      fail-fast: false
      matrix:
        # os: [ Gauss, LarioARM ]
        label: [ Gauss, LarioARM, LarioX64 ]
        # os: [ ubuntu-22.04 ]
      #   os: [ ubuntu-22.04, macos-15-intel, macos-15 ]
    runs-on:
      labels: [ 'self-hosted', "${{ matrix.label }}" ]

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set package name for linux
        if: runner.os == 'Linux'
        run: echo "PKGNAME=drsuite_${RELEASEVERSION}_linux_$(uname -m)" >> $GITHUB_ENV 

      - name: Set package name for mac
        if: runner.os == 'macOS'
        run: echo "PKGNAME=drsuite_${RELEASEVERSION}_mac_$(uname -m)" >> $GITHUB_ENV 

      - name: Set unix variables
        run: |
          echo "SHA_SHORT=$(git rev-parse --short "$GITHUB_SHA")" >> "$GITHUB_ENV"
          echo "PACKAGE=${PWD}/${PKGNAME}.zip" >> $GITHUB_ENV          

      - name: Set up MATLAB
        uses: matlab-actions/setup-matlab@v2
        id: setup-matlab
        with:
          cache: false
          release: ${{ env.MATLAB_VERSION }}
          products: >
            MATLAB_Compiler
            Image_Processing_Toolbox
            Medical_Imaging_Toolbox
            Parallel_Computing_Toolbox
            
      - name: Compile and package command-line tools
        uses: matlab-actions/run-command@v2
        with:
          command: package_drsuite("${{ env.RELEASEVERSION }}")
          
      - name: Save Binaries as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.PKGNAME}}
          path: ${{ env.PACKAGE }}
          overwrite: true

      # - name: Test 1D Workflow (MATLAB)
      #   uses: matlab-actions/run-command@v2
      #   with:
      #     command: "phantom_1d_workflow"

      # - name: Test 2D Workflow (MATLAB)
      #   uses: matlab-actions/run-command@v2
      #   with:
      #     command: "phantom_2d_workflow"          
          
      - name: Test 1D Workflow (Compiled)
        env:
          BrainSuiteMCR: ${{ steps.setup-matlab.outputs.matlabroot }}
        run: |
          mkdir test1D
          cd test1D
          unzip -q ${PACKAGE}
          cd ${PKGNAME}
          PATH="${PWD}/bin:$PATH"
          ./phantom_1d_workflow.sh

      # - name: Test 2D Workflow (Compiled)
      #   env:
      #     BrainSuiteMCR: ${{ steps.setup-matlab.outputs.matlabroot }}
      #   run: |
      #     PATH="${PWD}/bin:$PATH"
      #     ./phantom_2d_workflow.sh

      - name: Save Test Output as Artifact
        if: github.event_name != 'release'
        uses: actions/upload-artifact@v4
        with:
          name: Result-${{ env.SHA_SHORT }}
          path: Result
          overwrite: true
        
      - name: Publish ${{ env.PACKAGE }}
        if: github.event_name == 'release'
        uses: ncipollo/release-action@v1
        with:
          artifacts: "${{ env.PACKAGE }}"
          tag: ${{ env.RELEASEVERSION }}       
          allowUpdates: true
