name: Build DRSuite
run-name: Build DRSuite by @${{ github.actor }}

on:
  workflow_dispatch:
  release:
    types: [created]
  push:
    branches: [main, dev]
  # pull_request:
  #   branches: [main]
env:
  RELEASEVERSION: ${{ github.ref_name }}
  MLM_LICENSE_TOKEN: ${{ secrets.MATLAB_TOKEN }}
  MATLAB_VERSION: R2025b
jobs:
  build:
    permissions: write-all
    name: Build DRSuite
    strategy:
      fail-fast: false
      matrix:
        # os: [ Gauss, LarioARM ]
        label: [ Gauss, LarioARM ]
        # os: [ ubuntu-22.04 ]
      #   os: [ ubuntu-22.04, macos-15-intel, macos-15 ]
    runs-on:
      labels: [ 'self-hosted', "${{ matrix.label }}" ]

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set environment variables for linux
        if: runner.os == 'Linux'
        run: |
          echo "SHA_SHORT=$(git rev-parse --short "$GITHUB_SHA")" >> "$GITHUB_ENV"
          echo "PACKAGE=${PWD}/DRSuite_${RELEASEVERSION}_linux_x64.zip" >> $GITHUB_ENV

      - name: Set environment variables for mac
        if: runner.os == 'macOS'
        run: |
          echo "SHA_SHORT=$(git rev-parse --short "$GITHUB_SHA")" >> "$GITHUB_ENV"
          if [ $(uname -m) == "x86_64" ]; then
            echo "PACKAGE=${PWD}/DRSuite_${RELEASEVERSION}_mac_x64.zip" >> $GITHUB_ENV          
          else
            echo "PACKAGE=${PWD}/DRSuite_${RELEASEVERSION}_mac_ARM64.zip" >> $GITHUB_ENV
          fi

      - name: Set up MATLAB
        uses: matlab-actions/setup-matlab@v2
        id: setup-matlab
        with:
          cache: false
          release: ${{ env.MATLAB_VERSION }}
          products: >
            MATLAB_Compiler
            Image_Processing_Toolbox
            Medical_Imaging_Toolbox
            Parallel_Computing_Toolbox
            
      - name: Compile command-line tools
        uses: matlab-actions/run-command@v2
        with:
          command: "compile_cli"

      - name: make package
        run: |
          cp ini2struct/license.txt ini2struct_license.txt 
          cd ..
          zip -r "${PACKAGE}" ${{ github.event.repository.name }}/{bin,LICENSE.txt,readme.md,ini2struct_license.txt}
          
      - name: Save Binaries as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: drsuite_cli-${{ env.SHA_SHORT }}
          path: ${{ env.PACKAGE }}
          overwrite: true

      # - name: Test 1D Workflow (MATLAB)
      #   uses: matlab-actions/run-command@v2
      #   with:
      #     command: "phantom_1d_workflow"

      # - name: Test 2D Workflow (MATLAB)
      #   uses: matlab-actions/run-command@v2
      #   with:
      #     command: "phantom_2d_workflow"          
          
      - name: Test 1D Workflow (Compiled)
        env:
          BrainSuiteMCR: ${{ steps.setup-matlab.outputs.matlabroot }}
        run: |
          PATH="${PWD}/bin:$PATH"
          ./phantom_1d_workflow.sh

      - name: Test 2D Workflow (Compiled)
        env:
          BrainSuiteMCR: ${{ steps.setup-matlab.outputs.matlabroot }}
        run: |
          PATH="${PWD}/bin:$PATH"
          ./phantom_2d_workflow.sh

      - name: Save Test Output as Artifact
        if: github.event_name != 'release'
        uses: actions/upload-artifact@v4
        with:
          name: Result-${{ env.SHA_SHORT }}
          path: Result
          overwrite: true
        
      - name: Publish ${{ env.PACKAGE }}
        if: github.event_name == 'release'
        uses: ncipollo/release-action@v1
        with:
          artifacts: "${{ env.PACKAGE }}"
          tag: ${{ env.RELEASEVERSION }}       
          allowUpdates: true
