name: Build DRSuite for Windows
run-name: Build DRSuite (Win) by @${{ github.actor }}

on:
  workflow_dispatch:
  release:
    types: [created]
  push:
    branches: [windows]
  # pull_request:
  #   branches: [main]
env:
  RELEASEVERSION: ${{ github.ref_name }}
  MLM_LICENSE_TOKEN: ${{ secrets.MATLAB_TOKEN }}
jobs:
  build:
    permissions: write-all
    name: Build DRSuite
    strategy:
      fail-fast: false
      matrix:
        # os: [ubuntu-latest, macos-latest]
        os: [ windows ]
    runs-on:
      labels: [ self-hosted, "${{ matrix.os }}" ]

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set environment variables for Windows
        if: runner.os == 'Windows'
        run: |
          echo "SHA_SHORT=$(git rev-parse --short "$env:GITHUB_SHA")" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append
          echo "PACKAGE=${PWD}/DRSuite_${env:VERSION}_win_x64.zip" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append
          
      - name: Set up MATLAB
        uses: matlab-actions/setup-matlab@v2
        id: setup-matlab
        with:
          cache: false
          release: R2024b
          products: >
            MATLAB_Compiler
            Image_Processing_Toolbox
            Medical_Imaging_Toolbox
            Parallel_Computing_Toolbox
            
      - name: Compile command-line tools
        uses: matlab-actions/run-command@v2
        with:
          command: package_drsuite("${{ env.RELEASEVERSION }}")

      - name: Save Binaries as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.PKGNAME}}
          path: ${{ env.PACKAGE }}
          overwrite: true

      # - name: Test 1D Workflow (MATLAB)
      #   uses: matlab-actions/run-command@v2
      #   with:
      #     command: "phantom_1d_workflow"

      # - name: Test 2D Workflow (MATLAB)
      #   uses: matlab-actions/run-command@v2
      #   with:
      #     command: "phantom_2d_workflow"          
          
      # - name: Test 1D Workflow (Compiled)
      #   run: |
      #     ./phantom_1d_workflow.bat
      - name: Test 1D Workflow (Compiled)
        env:
          BrainSuiteMCR: ${{ steps.setup-matlab.outputs.matlabroot }}
        run: |
          mkdir test1D
          cd test1D
          # 7z x ${env:PACKAGE}
          Expand-Archive -Path "${env:PACKAGE}" -DestinationPath "${PWD}"
          cd ${env:PKGNAME}
          ./phantom_2d_workflow.bat
      # - name: Test 2D Workflow
      #   run: |
      #     ./phantom_2d_workflow.bat

      # - name: Save Test Output as Artifact
      #   if: github.event_name != 'release'
      #   uses: actions/upload-artifact@v4
      #   with:
      #     name: Result-${{ env.SHA_SHORT }}
      #     path: Result
      #     overwrite: true

      # # - name: Publish ${{ env.Package }}
      # #   if: github.event_name == 'release'
      # #   run: |
      # #     mv cli.zip "${{ env.Package }}"
        
      # - name: Publish ${{ env.PACKAGE }}
      #   if: github.event_name == 'release'
      #   uses: ncipollo/release-action@v1
      #   with:
      #     artifacts: "${{ env.PACKAGE }}"
      #     tag: ${{ env.RELEASEVERSION }}       
      #     allowUpdates: true
