name: Build DRSuite
run-name: Build DRSuite by @${{ github.actor }}

on:
  workflow_dispatch:
  release:
    types: [created]
  push:
    branches: [windows] #main, dev]
  # pull_request:
  #   branches: [main]
env:
#  RELEASEVERSION: ${{ github.ref_name }}
  RELEASEVERSION: 25a
  MLM_LICENSE_TOKEN: ${{ secrets.MATLAB_TOKEN }}
  MATLAB_VERSION: R2024b
jobs:
  build:
    permissions: write-all
    name: Build DRSuite
    strategy:
      fail-fast: false
      matrix:
        os: [ Egret ]
        # os: [ Gauss, LarioARM ]
        # label: [ Gauss, LarioARM ] #, LarioX64 ]
        # os: [ ubuntu-22.04, macos-15, windows-latest ]
      #   os: [ ubuntu-22.04, macos-15-intel, macos-15 ]
    runs-on:
      labels: [ "${{ matrix.os }}" ]

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set package name for linux
        if: runner.os == 'Linux'
        run: echo "PKGNAME=drsuite_${RELEASEVERSION}_linux_$(uname -m)" >> $GITHUB_ENV 

      - name: Set package name for mac
        if: runner.os == 'macOS'
        run: echo "PKGNAME=drsuite_${RELEASEVERSION}_mac_$(uname -m)" >> $GITHUB_ENV 

      - name: Set unix variables
        if: runner.os != 'Windows'
        run: |
          echo "SHA_SHORT=$(git rev-parse --short "$GITHUB_SHA")" >> "$GITHUB_ENV"
          echo "PACKAGE=${PWD}/${PKGNAME}.zip" >> $GITHUB_ENV          

      - name: Set environment variables for Windows
        if: runner.os == 'Windows'
        run: |
          echo "SHA_SHORT=$(git rev-parse --short "$env:GITHUB_SHA")" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append
          echo "PKGNAME=drsuite_${env:RELEASEVERSION}_win_x64" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append
          echo "PACKAGE=${PWD}/DRSuite_${env:RELEASEVERSION}_win_x64.zip" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append

      - name: Set up MATLAB
        uses: matlab-actions/setup-matlab@v2
        id: setup-matlab
        with:
          cache: true
          release: ${{ env.MATLAB_VERSION }}
          products: >
            MATLAB_Compiler
            Image_Processing_Toolbox
            Medical_Imaging_Toolbox
            Parallel_Computing_Toolbox
            
      - name: Compile and package command-line tools
        uses: matlab-actions/run-command@v2
        with:
          command: package_drsuite("${{ env.RELEASEVERSION }}")
          
      - name: Save Binaries as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.PKGNAME}}
          path: ${{ env.PACKAGE }}
          overwrite: true

      # - name: Test 1D Workflow (MATLAB)
      #   uses: matlab-actions/run-command@v2
      #   with:
      #     command: "phantom_1d_workflow"

      # - name: Test 2D Workflow (MATLAB)
      #   uses: matlab-actions/run-command@v2
      #   with:
      #     command: "phantom_2d_workflow"          

      - name: Setup for tests
        if: runner.os == 'Windows'
        run: |
          mkdir test1D
          mkdir test2D
          Expand-Archive -Path "${env:PACKAGE}" -DestinationPath "${PWD}/test1D"
          Expand-Archive -Path "${env:PACKAGE}" -DestinationPath "${PWD}/test2D"

      - name: Setup for tests
        if: runner.os != 'Windows'
        run: |
          install -d test1D
          install -d test2D
          unzip -q ${PACKAGE} -d test1D
          unzip -q ${PACKAGE} -d test2D

      - name: Test 1D Workflow (Compiled)
        env:
          BrainSuiteMCR: ${{ steps.setup-matlab.outputs.matlabroot }}
        working-directory: test1D/${{ env.PKGNAME}}
        run: ./phantom_1d_workflow.sh

      - name: Save Test Output as Artifact
        if: github.event_name != 'release'
        uses: actions/upload-artifact@v4
        with:
          name: Result1D-${{ env.SHA_SHORT }}
          path: test1D/${{ env.PKGNAME}}/Result
          overwrite: true

      # - name: Test 2D Workflow (Compiled)
      #   env:
      #     BrainSuiteMCR: ${{ steps.setup-matlab.outputs.matlabroot }}
      #   run: |
      #     PATH="${PWD}/bin:$PATH"
      #     ./phantom_2d_workflow.sh

        
      - name: Publish ${{ env.PACKAGE }}
        if: github.event_name == 'release'
        uses: ncipollo/release-action@v1
        with:
          artifacts: "${{ env.PACKAGE }}"
          tag: ${{ env.RELEASEVERSION }}       
          allowUpdates: true
